##################################
#Author: Joe Meier a.k.a Jocomol #
#Contact: joelmeier08@gmail.com  #
##################################
#DO ONLY CHANGE THE VALUES AND NOT THE KEYS
Config:
  - intervalMeasurementTime:
    day: 0
    hour: 0
    minute: 5

  - updateInterval:
    day: 14
    hour: 0
    minute: 0
