##################################
#Author: Joe Meier a.k.a Jocomol #
#Contact: joelmeier08@gmail.com  #
##################################
#DO ONLY CHANGE THE VALUES AND NOT THE NAMES
Config:
  - intervalMeasurementTime:
    days: 0
    hours: 0
    minutes: 5
    seconds: 0
    
  - updateInterval:
    days: 14
    hours: 0
    minutes: 0
    seconds: 0
